export const LANDING = '/'; //Missing
export const SIGN_UP = '/signUp';
export const SIGN_IN = '/signIn'; //Missing Google Setup in Firestore
export const HOME = '/home'; //Show options based on role
export const UCONFIG = '/uConfig'; //It's like it's done, but still missing some testing
export const OVERVIEW = '/overview'; //Late on this one
export const CREATEIDEA = '/createIdea'; //Configure button, fetch and save
export const DESCIDEA = '/descIdea/:id'; // Configure buttons and fetch
export const LISTIDEA= '/listIdea'; //Configure fetch and buttons
export const UPDATEIDEA = '/updateIdea/:id';
export const BANDEJA = '/bandeja';
export const FINANCIST = '/financist';
export const BOOKMARK = '/financist/bookmark';
export const VIDEOCHAT = '/videochat';
// export const ACCOUNT = '/account';
// export const ADMIN = '/admin';
// export const PASSWORD_FORGET = '/pw-forget';